sac:
  env: navix/Navix-GoToDoor-6x6-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  buffer_size: 65536
  fill_buffer: 8192
  batch_size: 128
  learning_rate: 0.0003
  gradient_steps: 128
  total_timesteps: 1048576
  eval_freq: 16384
  gamma: 0.9
  tau: 0.95
  target_entropy_ratio: 0.5
  normalize_observations: false

ppo:
  env: navix/Navix-GoToDoor-6x6-v0
  agent_kwargs:
    activation: tanh
  num_envs: 16
  num_steps: 128
  num_epochs: 1
  num_minibatches: 8
  learning_rate: 0.0003
  max_grad_norm: 0.5
  total_timesteps: 1048576
  eval_freq: 16384
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  normalize_observations: false

dqn:
  env: navix/Navix-GoToDoor-6x6-v0
  agent_kwargs:
    activation: tanh
  num_envs: 128
  gradient_steps: 128
  buffer_size: 65536
  fill_buffer: 8192
  batch_size: 128
  learning_rate: 0.0003
  max_grad_norm: 10
  total_timesteps: 1048576
  eval_freq: 16384
  gamma: 0.99
  eps_start: 1.0
  eps_end: 0.05
  exploration_fraction: 0.5
  target_update_freq: 2048
  ddqn: true
  normalize_observations: false
