name: SAC
author: keraJLi
paper_url: https://arxiv.org/abs/1801.01290
navix_commit_url: https://github.com/epignatelli/navix/commit/3c0671d732223afe43bd7bf8fe2071fe18033cd7
algorithm_commit_url: https://github.com/keraJLi/rejax/commit/d7510951b7a89ca8463cb2a6d18e21750ec454ff
